# Generated by Django 2.2 on 2020-11-03 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hopscotch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories_routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_event', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='writers.Comment')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColaboratorAndStoryRouter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writers.Colaborator')),
                ('story_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories_routes.StoryRoute')),
            ],
        ),
        migrations.CreateModel(
            name='ColaboratorAndHopscotch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writers.Colaborator')),
                ('hopscotch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopscotch.Hopscotch')),
            ],
        ),
        migrations.AddField(
            model_name='colaborator',
            name='hopscotch',
            field=models.ManyToManyField(through='writers.ColaboratorAndHopscotch', to='hopscotch.Hopscotch'),
        ),
        migrations.AddField(
            model_name='colaborator',
            name='story_route',
            field=models.ManyToManyField(through='writers.ColaboratorAndStoryRouter', to='stories_routes.StoryRoute'),
        ),
        migrations.AddField(
            model_name='colaborator',
            name='writer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
