# Generated by Django 2.2 on 2020-11-03 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hopscotch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HopscotchAndStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hopscotch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopscotch.Hopscotch')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Story')),
            ],
        ),
        migrations.AddField(
            model_name='hopscotch',
            name='story',
            field=models.ManyToManyField(through='hopscotch.HopscotchAndStory', to='stories.Story'),
        ),
    ]
