# Generated by Django 2.2 on 2020-11-04 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopscotch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hopscotch',
            options={'permissions': (('can_be_admin', 'Can be admin'),)},
        ),
    ]
