# Generated by Django 2.2 on 2020-11-06 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopscotch', '0003_hopscotch_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopscotch',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
