# Generated by Django 2.2 on 2020-11-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
