# Generated by Django 2.2 on 2020-11-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201104_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='signing',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
