# Generated by Django 2.2 on 2020-11-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201104_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
