# Generated by Django 2.2 on 2020-11-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201104_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
