# Generated by Django 2.2 on 2020-11-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_writer_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='writer_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
