# Generated by Django 2.2 on 2020-11-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_writer_writer_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='writer_level',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
